// GENERATED by tools/seo/build.js from index.html PAGE_SEO — do not edit by hand.
// Netlify Edge Function: gives each single-page-app route its own <title>,
// meta description, canonical, Open Graph/Twitter tags and robots directive
// in the HTML that crawlers receive (index.html is served for every route,
// and only JavaScript used to apply these per route). If anything fails,
// Netlify serves the unmodified page (onError: 'bypass').
export const ROUTES = {
  "/login": {
    "title": "Login | OrivenAI",
    "desc": "Log in to your OrivenAI account to manage your advertising campaigns.",
    "noindex": true
  },
  "/signup": {
    "title": "Create Your Account | OrivenAI",
    "desc": "Create a free OrivenAI account to start creating, launching and managing advertising campaigns.",
    "noindex": true
  },
  "/terms": {
    "title": "Terms of Service | OrivenAI",
    "desc": "Terms of Service for using the OrivenAI advertising platform.",
    "noindex": false
  },
  "/privacy": {
    "title": "Privacy Policy | OrivenAI",
    "desc": "How OrivenAI collects, uses and protects your data.",
    "noindex": false
  },
  "/refund-policy": {
    "title": "Refund Policy | OrivenAI",
    "desc": "OrivenAI’s refund policy for subscriptions and credits.",
    "noindex": false
  },
  "/cookie-policy": {
    "title": "Cookie Policy | OrivenAI",
    "desc": "How OrivenAI uses cookies on this website.",
    "noindex": false
  },
  "/security": {
    "title": "Security | OrivenAI",
    "desc": "How OrivenAI protects your advertising accounts and data.",
    "noindex": false
  },
  "/contact": {
    "title": "Contact | OrivenAI",
    "desc": "Get in touch with the OrivenAI team.",
    "noindex": false
  },
  "/about": {
    "title": "About OrivenAI | AI Advertising Platform",
    "desc": "Marketing data is scattered across platforms. Oriven brings it together so you can spend less time in dashboards and more time making better decisions.",
    "noindex": false
  },
  "/blog": {
    "title": "Blog | OrivenAI",
    "desc": "Insights, updates and ideas from the Oriven team.",
    "noindex": false
  },
  "/product": {
    "title": "Connect Your Advertising Platforms | OrivenAI",
    "desc": "Oriven connects to Google Ads, Meta Ads, TikTok Ads and Pinterest Ads. Research, creative, launch, campaign management and automation in one workspace.",
    "noindex": false
  },
  "/solutions": {
    "title": "Advertising Solutions | OrivenAI",
    "desc": "Every Oriven solution maps to one real product: no generic promises, just the actual thing that fixes it.",
    "noindex": false
  },
  "/case-studies": {
    "title": "Case Studies | OrivenAI",
    "desc": "Illustrative examples of how Oriven changes a real advertising workflow.",
    "noindex": false
  },
  "/pricing": {
    "title": "Pricing | OrivenAI",
    "desc": "OrivenAI pricing plans and credits for AI advertising creation, research, launch, campaign management and automation.",
    "noindex": false
  },
  "/faq": {
    "title": "FAQ | OrivenAI",
    "desc": "Answers to common questions about OrivenAI, credits, connecting ad accounts and plans.",
    "noindex": false
  },
  "/product/google-ads": {
    "title": "AI Google Ads Management: Create, Launch & Automate | OrivenAI",
    "desc": "Manage Google Ads with AI: OrivenAI builds Search, Performance Max and Demand Gen campaigns from a brief, launches them through Google’s API, tracks results and runs rules you set.",
    "noindex": false
  },
  "/product/meta-ads": {
    "title": "Meta Ads Automation for Facebook & Instagram | OrivenAI",
    "desc": "Create Facebook and Instagram campaigns from a brief, launch them through Meta’s API, track results and automate pause, resume and budget rules with OrivenAI Autopilot.",
    "noindex": false
  },
  "/product/tiktok-ads": {
    "title": "TikTok Ads AI & Campaign Workflow | OrivenAI",
    "desc": "Connect TikTok Ads to Oriven. Create and launch campaigns through TikTok’s own API, alongside Google, Meta and Pinterest.",
    "noindex": false
  },
  "/product/pinterest-ads": {
    "title": "Pinterest Ads AI & Campaign Workflow | OrivenAI",
    "desc": "Connect Pinterest Ads to Oriven. Create your ad account, build campaigns and launch Pins through Pinterest’s own API.",
    "noindex": false
  },
  "/create": {
    "title": "AI Ad Creation & Creative Workspace | OrivenAI",
    "desc": "The Creative Playground turns a product description into platform-ready ad creative, image or video, informed by your real Business and Brand context.",
    "noindex": false
  },
  "/launch": {
    "title": "Campaign Launch & AI Ad Generation | OrivenAI",
    "desc": "Describe your product, choose your platforms, and Oriven generates a complete, ready-to-publish campaign: strategy, structure and creative included.",
    "noindex": false
  },
  "/campaigns": {
    "title": "Campaign Management & Tracking | OrivenAI",
    "desc": "Track live campaigns, pick up drafts, and review every detail before anything publishes, across Google, Meta and TikTok, all in one place.",
    "noindex": false
  },
  "/research": {
    "title": "AI Advertising Research | OrivenAI",
    "desc": "Understand creative approaches, messaging patterns and advertising trends outside your own campaigns, so you can test the right ideas, not guess.",
    "noindex": false
  },
  "/autopilot": {
    "title": "Advertising Automation | OrivenAI",
    "desc": "Autopilot turns campaign insights into automated action, reallocating wasted budget and flagging audience fatigue, based on rules you control.",
    "noindex": false
  },
  "/business": {
    "title": "Brand Context for AI Advertising | OrivenAI",
    "desc": "Your business profile and Brand Identity give every AI generation the same context, so campaigns, copy and creative actually sound like you.",
    "noindex": false
  },
  "/blog/oriven-ai-is-now-live": {
    "title": "Oriven AI Is Now Live | OrivenAI Blog",
    "desc": "After months of planning, designing and building, Oriven is officially live. Learn more about our mission and what’s coming next for the platform.",
    "noindex": false
  },
  "/blog/what-you-can-do-with-oriven": {
    "title": "What You Can Do With Oriven | OrivenAI Blog",
    "desc": "Discover how Oriven helps marketers and businesses connect advertising data, generate insights and make better decisions from one platform.",
    "noindex": false
  },
  "/blog/why-we-built-oriven": {
    "title": "Why We Built Oriven | OrivenAI Blog",
    "desc": "Marketing data is fragmented across multiple platforms. Learn how that challenge inspired the creation of Oriven and the vision behind the platform.",
    "noindex": false
  }
};

const ORIGIN = 'https://orivenai.com';
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Rewrites only the tags index.html marks for this purpose (ids ov*), plus
// <title> and the meta description. Returns the HTML unchanged if a tag is missing.
export function rewriteHead(html, pathname) {
  const seo = ROUTES[pathname];
  if (!seo) return html;
  const url = ORIGIN + pathname;
  const t = esc(seo.title), d = esc(seo.desc);
  const setContent = (h, id, v) => h.replace(new RegExp('(<meta[^>]*\\bcontent=")[^"]*("[^>]*\\bid="' + id + '")'), '$1' + v + '$2');
  let h = html.replace(/<title>[^<]*<\/title>/, '<title>' + t + '</title>');
  h = h.replace(/(<meta name="description" content=")[^"]*(")/, '$1' + d + '$2');
  h = h.replace(/(<link rel="canonical" href=")[^"]*(" id="ovCanonical")/, '$1' + url + '$2');
  h = setContent(h, 'ovOgTitle', t);
  h = setContent(h, 'ovOgDesc', d);
  h = setContent(h, 'ovOgUrl', url);
  h = setContent(h, 'ovTwTitle', t);
  h = setContent(h, 'ovTwDesc', d);
  h = setContent(h, 'ovRobotsMeta', seo.noindex ? 'noindex, follow' : 'index, follow');
  return h;
}

export default async (request, context) => {
  const { pathname } = new URL(request.url);
  if (!ROUTES[pathname]) return;
  const res = await context.next();
  const type = res.headers.get('content-type') || '';
  if (res.status !== 200 || !type.includes('text/html')) return res;
  const html = await res.text();
  const headers = new Headers(res.headers);
  headers.delete('content-length');
  headers.delete('etag');
  return new Response(rewriteHead(html, pathname), { status: res.status, headers });
};

export const config = {
  path: ["/about","/autopilot","/blog","/blog/oriven-ai-is-now-live","/blog/what-you-can-do-with-oriven","/blog/why-we-built-oriven","/business","/campaigns","/case-studies","/contact","/cookie-policy","/create","/faq","/launch","/login","/pricing","/privacy","/product","/product/google-ads","/product/meta-ads","/product/pinterest-ads","/product/tiktok-ads","/refund-policy","/research","/security","/signup","/solutions","/terms"],
  onError: 'bypass',
};
